sudo: false

language: c

# We're configured elsewhere to build PRs. The only branch that needs to be
# built automatically is master.
branches:
  only:
    - "master"

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.local
    - $HOME/.stack

# We set the compiler values here to tell Travis to use a different
# cache file per set of arguments.
matrix:
  include:
  - env: STACK_ARGS="--no-nix"
    compiler: ": #stack linux"
    # Until travis-ci/apt-package-whitelist#379 is fixed, we have to install
    # manually.
    before_install:
      - unset CC
      - mkdir -p $HOME/.local/bin
      - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C $HOME/.local/bin '*/stack'

  # Build on OS X in addition to Linux
  - env: STACK_ARGS="--no-nix"
    compiler: ": #stack osx"
    os: osx
    before_install:
      - unset CC
      - mkdir -p $HOME/.local/bin
      - travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
      - |
        brew update
        brew install pcre

install:
  - stack --no-terminal --install-ghc $STACK_ARGS test --bench --only-dependencies

script:
  - stack --no-terminal $STACK_ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
