sudo: false

language: c

# We're configured elsewhere to build PRs. The only branch that needs to be
# built automatically is master.
branches:
  only:
    - "master"

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.local
    - $HOME/.stack

# We set the compiler values here to tell Travis to use a different
# cache file per set of arguments.
#
# If you need to have different apt packages for each combination in the
# matrix, you can use a line such as:
#     addons: {apt: {packages: [libfcgi-dev,libgmp-dev]}}
matrix:
  include:
  - env: STACK_ARGS="--no-nix"
    compiler: ": #stack linux"
    addons:
      apt:
        packages:
          - stack
        sources:
          - fpcomplete-trusty

  # Build on OS X in addition to Linux
  - env: STACK_ARGS="--no-nix"
    compiler: ": #stack osx"
    os: osx
    before_install:
      - travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
      - |
        brew update
        brew install pcre

install:
  - stack --no-terminal --install-ghc $STACK_ARGS test --bench --only-dependencies

script:
  - stack --no-terminal $STACK_ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
