resolver: lts-7.1

packages:
- '.'

extra-deps:
  - diff-parse-0.2.1
  - highlighter2-0.2.5

# jml uses 'nix' to build on Darwin. These are the non-Haskell packages
# required.
nix:
  packages:
    - pcre
    - pkgconfig
