# We're only supporting GHC 8.0+, and we're not offering any library suppoort,
# so OK to use nightly for now.
resolver: nightly-2016-08-27

packages:
- '.'

extra-deps:
  - diff-parse-0.2.1
  - highlighter2-0.2.5

# jml uses 'nix' to build on Darwin. These are the non-Haskell packages
# required.
nix:
  enable: false
  packages:
    - pcre
    - pkgconfig
